enable-magisk-update = true
parallel-jobs = 1
patches-version = "dev"
cli-version = "dev"

[Spotify]
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
arch = "arm64-v8a"

[YouTube]
build-mode = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
