enable-magisk-update = true
parallel-jobs = 1
patches-version = "dev"
cli-version = "dev"

[Spotify]
uptodown-dlurl = "https://spotify.en.uptodown.com/android"

[YouTube-Extended]
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
