enable-magisk-update = true
parallel-jobs = 1
patches-version = "dev"
cli-version = "dev"

[YouTube-Extended]
enabled = false
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

[Spotify]
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
